### PR TITLE
add gradle support

### LINKED ISSUE #24: Add Gradle support
/cc @atomfrede

### PR DESCRIPTION
**Pull request by atomfrede**
This PR is work in progress. It r[equires additional needles](https://github.com/jhipster/generator-jhipster/pull/18199) in main generator and some additional adjustments to add the native image configuration to build.gradle afterwards.

closes #24

### CODE REVIEW

**Comment by atomfrede** [comment]
The generation for gradle should be complete, I am getting compile errors with native compile. Will try to find whats wrong as I can't see a difference compared to the maven part (maybe something related to updates we have done in the main generator?)

```
> Task :generateAot FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/logging/LogFile
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:93)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.springframework.aot.build.GenerateBootstrapCommand.main(GenerateBootstrapCommand.java:112)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.logging.LogFile
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 10 more
```

**Comment by mraible** [comment]
@atomfrede Does JHipster v7.8.0 help solve this problem?

**Comment by atomfrede** [comment]
Will give a try this evening.

**Comment by atomfrede** [comment]
I think I have found the problem.  It seems to be related to spring boot > 2.6.4. Downgrading the version makes the aot compiling work with gradle. With maven it seems to work with 2.6.6 too. 

image

**Comment by mraible** [comment]
Nice work! It looks like 0.11.4 has only a few issues remaining. We can try again when it's released. https://github.com/spring-projects-experimental/spring-native/milestones

File: generators/server/generator.mjs [hunk 1]
```diff
@@ -40,126 +41,149 @@ export default class extends GeneratorBaseEntities {
       },
 
       async pomXml({ application: { buildToolMaven } }) {
```
Comment (mshima) [inline generators/server/generator.mjs:43]: It would be better to extract gradle to another task instead of reusing pomXml.
IMO keeps a bit easier to understand.
```suggestion
      async customizeGradle({ application: { buildToolGrade } }) {
        if (! buildToolGrade) return;
      }

      async customizeMaven({ application: { buildToolMaven } }) {
```

Comment (mshima) [inline generators/server/generator.mjs:43]: It would be better to extract gradle to another task instead of reusing pomXml.
IMO keeps a bit easier to understand.
```suggestion
      async customizeGradle({ application: { buildToolGrade } }) {
        if (! buildToolGrade) return;
      }

      async customizeMaven({ application: { buildToolMaven } }) {
```

**Comment by atomfrede** [comment]
Very strange. Using boot 2.6.4 and 0.11.3 works fine. With 2.6.6 and 0.11.4 I have now another failure:

```
Execution optimizations have been disabled for task ':generateAot' to ensure correctness due to the following reasons:
  - Additional action of task ':generateAot' was implemented by the Java lambda 'org.springframework.aot.gradle.SpringAotGradlePlugin$$Lambda$777/0x000000080074a3d0'. Reason: Using Java lambdas is not supported as task inputs. Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#implementation_unknown for more details about this problem.
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/logging/LogFile
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:93)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.springframework.aot.build.GenerateBootstrapCommand.main(GenerateBootstrapCommand.java:112)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.logging.LogFile
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 10 more
```

**Comment by atomfrede** [comment]
But it seems to be something with jhipster. The example from start.spring.io works fine with boot 2.6.6 and aot 0.11.4. Will see what might be the problem.

**Comment by mshima** [comment]
I’ve added build tool to workflow

**Comment by atomfrede** [comment]
Thanks @mshima

**Comment by atomfrede** [comment]
Looks like it's related to spring boot dev tools and developmentOnly configuration. https://github.com/spring-projects-experimental/spring-native/issues/1579 Will try to remove them for now at least aot compilation/generation works.

**Comment by atomfrede** [comment]
No idea why the gradle unit tests are failing in ci, running them locally just works fine. Native image still building, so at least that looks fine to me.

**Comment by atomfrede** [comment]
Thanks @mshima for taking care of the undertow replacement. Are we using psql + h2 for testing in ci? I used psql for both, thats why generateAot worked for me. Will have look how to handle that bean

**Comment by atomfrede** [comment]
🚀 Looks like you've been faster

**Comment by mshima** [comment]
It's a bug at jhipster?
h2 dependencies were supposed to be at https://github.com/jhipster/generator-jhipster/blob/7096814a2ff241963f5cef11a9279c06712802fb/generators/server/templates/gradle/profile_dev.gradle.ejs#L19-L22?

**Comment by atomfrede** [comment]
You maybe right, think so too. Will have a look.

**Comment by mshima** [comment]
Still failing, I will let you continue.

**Comment by atomfrede** [comment]
I am still a little confused, created an app with h2, psql and webflux, generateAot works just fine (but using jdk instead of graalvm). But the bean h2TcpServer seems indeed not compatible, as it is created via reflection and the init and destroy methods must be called via reflection I guess.

**Comment by mraible** [comment]
I was never able to get H2 working. It's listed as a known issue. https://github.com/mraible/spring-native-examples#known-issues

**Comment by atomfrede** [comment]
Thanks @mraible for the heads up. I deactivated the h2 server bean for now, let's see if it works. By the way, do you have graal vm installed on your m1 mac? And if yes how? (not via sdkman at least I can't see it).

**Comment by mraible** [comment]
Here's how I installed GraalVM on my M1:

```
# Downloaded and expanded graalvm-ce-java17-darwin-aarch64-dev.tar.gz from https://github.com/graalvm/graalvm-ce-dev-builds/releases/download/22.2.0-dev-20220326_0133/graalvm-ce-java17-darwin-aarch64-dev.tar.gz
 mv ~/Downloads/graalvm-ce-java17-22.2.0-dev/Contents/Home ~/.sdkman/candidates/java/22.2.0.dev.r17-grl
 sudo xattr -r -d com.apple.quarantine ~/.sdkman/candidates/java/22.2.0.dev.r17-grl
 sdk default java 22.2.0.dev.r17-grl
 ```

Also documented by Josh Long:

https://joshlong.com/jl/blogPost/graalvm-on-apple-m1-arm-computers.html

**Comment by atomfrede** [comment]
Will switch to linux this evening to see whats wrong with nativeCompile step, at least it seems we are on the right track.

**Comment by atomfrede** [comment]
It is so strange the gradle and maven native compile seem to be so different for our use case, but I will have a detailed look later today.

**Comment by mshima** [comment]
`assemble nativeCompile` failed due to memory.
Custom allocated memory is set by `bootBuildImage`.
Switched to it.

**Comment by atomfrede** [comment]
> `assemble nativeCompile` failed due to memory. Custom allocated memory is set by `bootBuildImage`. Switched to it.

Thanks. Was not sure which command to use, guess I picked the wrong one

**Comment by atomfrede** [comment]
Seems like still memory issues. How do we pass the arguments?

**Comment by mshima** [comment]
Build succeed:
```
jhipster@0.0.1-SNAPSHOT postnative-package
[570](https://github.com/jhipster/generator-jhipster-native/runs/6126951317?check_suite_focus=true#step:17:570)
> cp build/libs/* build/native-executable
[571](https://github.com/jhipster/generator-jhipster-native/runs/6126951317?check_suite_focus=true#step:17:571)

[572](https://github.com/jhipster/generator-jhipster-native/runs/6126951317?check_suite_focus=true#step:17:572)
cp: target 'build/native-executable' is not a directory
```

**Comment by atomfrede** [comment]
🎉 I looked the max os builds, exit code 137. I will try it on my linux machine later to see where or if the native executable is created. Now I remember why I choose `nativeCompile`, as thats supposed to create a native executable like `mvn -Pnative -DskipTests package`.

**Comment by atomfrede** [comment]
[From the spring examples](https://github.com/spring-projects-experimental/spring-native/blob/5057a3d3d82b1acfd14703364cb43794ec4cab91/scripts/test.sh#L45) it seems like it is located in `build/native/nativeCompile`

File: generators/server/generator.mjs [hunk 2]
```diff
@@ -24,23 +24,73 @@ export default class extends GeneratorBaseEntities {
...
+          this.packageJson.merge({
+            scripts: {
+              'native-package': './mvnw package -Pnative,prod -DskipTests',
+              'native-start': './target/native-executable',
+            },
+          });
+        } else if (buildToolGradle) {
+          this.packageJson.merge({
+            scripts: {
+              'postnative-package': 'cp build/libs/* build/native-executable',
```
Comment (atomfrede) [inline generators/server/generator.mjs:44]:
```suggestion
              'postnative-package': 'cp build/libs/* build/native/nativeCompile',
```

File: generators/server/generator.mjs [hunk 3]
```diff
@@ -24,23 +24,73 @@ export default class extends GeneratorBaseEntities {
...
+              'native-package': './gradlew bootBuildImage -Pnative,prod -x test -x integrationTest',
+              'native-start': './build/native-executable',
```
Comment (atomfrede) [inline generators/server/generator.mjs:46]:
```suggestion
              'native-start': './build/native/nativeCompile',
```

**Comment by mshima** [comment]
Probably we will need to use `nativeCompile` task passing the memory argument.
bootBuildImage uses a docker image.
Seems that maven is not using docker.

File: generators/server/generator.mjs [hunk 4]
```diff
@@ -24,23 +24,73 @@ export default class extends GeneratorBaseEntities {
...
+          this.packageJson.merge({
+            scripts: {
+              'native-package': './mvnw package -Pnative,prod -DskipTests',
+              'native-start': './target/native-executable',
+            },
+          });
+        } else if (buildToolGradle) {
+          this.packageJson.merge({
+            scripts: {
+              'postnative-package': 'cp build/libs/* build/native/nativeCompile',
```
Comment (mshima) [inline generators/server/generator.mjs:44]:
```suggestion
              'postnative-package': 'cp build/native/nativeCompile/* build/native-executable',
```

File: generators/server/generator.mjs [hunk 5]
```diff
@@ -24,23 +24,73 @@ export default class extends GeneratorBaseEntities {
...
+              'native-package': './gradlew bootBuildImage -Pnative,prod -x test -x integrationTest',
+              'native-start': './build/native/nativeCompile',
```
Comment (mshima) [inline generators/server/generator.mjs:46]:
```suggestion
              'native-start': './build/native-executable',
```

**Comment by atomfrede** [comment]
Yes, I think we need nativeCompile with incrased memory

**Comment by atomfrede** [comment]
Spring native plugin uses the graal native plugin under the hood, so I think we can configure the nativeCompile task with the required options.

**Comment by atomfrede** [comment]
:tada: Good news, native compilation with gradle is running now. Very strange as the documentation seems plain wrong to some extend. Creating an example via start.spring.io does not work out of box for me. But maybe I have messed up with my jdk installations. 
Anyways, will update this PR and afterwards try to rebase

**Comment by atomfrede** [comment]
Oh boy, it seems I have messed up the whole rebase :(

File: generators/server/generator.mjs [hunk 6]
```diff
@@ -309,15 +394,33 @@ class `
...
-          this.editFile('pom.xml', contents => contents.replaceAll('undertow', 'tomcat'));
+          if (buildToolMaven) {
+            this.editFile('pom.xml', contents => contents.replaceAll('undertow', 'tomcat'));
 
-          this.editFile(`${SERVER_TEST_SRC_DIR}${packageFolder}/config/WebConfigurerTest.java`, contents =>
-            contents
-              .replace('import org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory;\n', '')
-              .replace(/    @Test\n    void shouldCustomizeServletContainer\(\)([\s\S]*?)\n    }/, '')
-          );
+            this.editFile(`${SERVER_TEST_SRC_DIR}${packageFolder}/config/WebConfigurerTest.java`, contents =>
```
Comment (mshima) [inline generators/server/generator.mjs:402]: Needs to be moved out of maven condition.

**Comment by atomfrede** [comment]
So finally all green! Thanks @mshima for the last adjustments and all your help!

**Comment by mshima** [comment]
Testing with h2TcpServer disabled, it shouldn’t  be required.

File: generators/server/generator.mjs [hunk 7]
```diff
@@ -24,26 +24,102 @@ export default class extends GeneratorBaseEntities {
...
+        }
+
+        const buildArgs = ['--no-fallback'];
+        let verbose = false;
+        let memory = '';
+        if (process.env.GITHUB_ACTIONS) {
+          verbose = true;
+          memory = process.platform === 'darwin' ? '-J-Xmx13g' : '-J-Xmx7g';
+          buildArgs.push('--verbose', process.platform === 'darwin' ? '-J-Xmx13g' : '-J-Xmx7g');
+        }
```
Comment (mshima) [inline generators/server/generator.mjs:87]: The missing bit to get maven feature parity is external options.
So we can drop this workaround.
https://github.com/jhipster/generator-jhipster-native/blob/fa4d064fb9060627c6d28c92057493910b32e3b7/.github/workflows/jdl.yml#L59

I wonder if it's possible.

Comment (atomfrede) [reply generators/server/generator.mjs:87]: Sadly they don't tell which can be set via cli :(

```
For options that can be set using command-line, if both DSL and command-line options are present, command-line options take precedence. 
```

Comment (atomfrede) [reply generators/server/generator.mjs:87]: Ah good to know. Let me check. I think we could do something like -PnativeBuildArgs=-J-Xmx13g....

Comment (atomfrede) [reply generators/server/generator.mjs]: I hope my changes to jdl are correct. I have added following properties: nativeBuildArgs (for nativeCompile) and nativeImageProperties (maybe we use ...Args here too) which can be used via -PnativeBuildArgs=-J-Xmx13g for example

**Comment by atomfrede** [comment]
@mraible I think we are ready to go. 

Unrelated question, are doing something special to start keycloak on your mac? I have some error which relates to udp/broadcasting as it seems. As a result keycloak is not reachable. I guess it's somehow related to docker 4 mac network settings or so, but no idea how to find out whats going on.

**Comment by mraible** [comment]
@atomfrede Are you using an M1? If so, you have to build Keycloak locally. Instructions were recently added to our docs. https://www.jhipster.tech/security/#keycloak

**Comment by mshima** [comment]
I am using `ghcr.io/marcelcoding/keycloak:15.0.2` image, there are others.

**Comment by atomfrede** [comment]
> @atomfrede Are you using an M1? If so, you have to build Keycloak locally. Instructions were recently added to our docs. https://www.jhipster.tech/security/#keycloak

Yes exactly. Found that issue on github, but thought it must be easier, thanks.

**Comment by atomfrede** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/74270

**Comment by pascalgrimaud** [comment]
@atomfrede : approved
